evalucom/beds/urls.py
from django.urls import path

from . import views

app_name='beds'
urlpatterns = [ 
    path('<int:offset>/', views.voyage, name='voyage'),
    path('', views.voyage, name='voyage'),
    path('add_bed/<int:home_id>', views.add_bed, name="add_bed"),
    path('index', views.index, name="index")
]

evalucom/evalucom/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('beds.urls'))
]

evalucom/beds/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.

class Bed(models.Model):
    res_beds = models.IntegerField(null=True)
    res_dem_beds = models.IntegerField(null=True)
    nus_beds = models.IntegerField(null=True)
    nus_dem_beds = models.IntegerField(null=True)
    
class Home(models.Model):
    name = models.CharField(max_length=200)
    vacant_beds = models.IntegerField(null=True)
    beds = models.ForeignKey(Bed, on_delete=models.CASCADE)
    page_number = models.IntegerField(default=0)

    def __str__(self):
        return self.name

evalucom/beds/views.py
import requests
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpRequest
from django.urls import reverse

from .models import Home, Bed

#This is where the user is rerouted if want to make a change to the amount of vacant beds. 
def index(request):
    all_homes = Home.objects.all()
    home_list = list()
    for home in all_homes:
        home_id = home.id
        page_number = home.page_number
        home_name = home.name
        home_beds = home.beds
        home_vacant_beds = home.vacant_beds
        if home.vacant_beds == None or home.vacant_beds == 'null':
            home.vacant_beds = 0
        
        if home_beds.res_beds != None:
            res = home_beds.res_beds
        else: 
            res = None
        if home_beds.res_dem_beds != None:
            res_dem = home_beds.res_dem_beds
        else: 
            res_dem = None
        if home_beds.nus_beds != None:
            nus = home_beds.nus_beds
        else: 
            nus = None
        if home_beds.nus_dem_beds != None:
            nus_dem = home_beds.nus_dem_beds
        else: 
            nus_dem = None
        home_list.append((home_vacant_beds,home_name, home_id,home_beds,res,res_dem,nus,nus_dem, home_id))      
    
    stuff = {
        'home_list': home_list,
        'page_number': page_number
    }
    return render(request, 'beds/stuff.html',stuff)

#This is the base view for the application, the data from the API is retireved from here
def voyage(request, offset = 0):
    page_number = offset
    #reset the database so that the data base doesnt get over populated
    hello = Home.objects.all()
    hello.delete()
    #this will change the page
    if 'previous' in request.GET:
        print("next")
        page_number = offset-1
    elif 'next' in request.GET:
        print('hello')
        page_number = offset+1
    #The url for the API, i change it based on the page number which is set by the user when they jump to and from different pages
    url = 'https://skills-assessment.herokuapp.com/api/skills_assessment/?limit=10&offset={}0'.format(page_number)

    response = requests.get(url)
    data = response.json()
    results = data['results']
    #get all the data from the URL an put into varaibles so that it can be displayed on the webpage
    home_list = list()
    for name in results:
        home_id = int(name['id'].split('-')[1])
        home_name = name['name']
        home_beds = name['beds']
        home_vacant_beds = name['vacant_beds']
        if home_vacant_beds == None or home_vacant_beds == 'null':
            home_vacant_beds = 0
        if 'Residential' in home_beds:
            res_bed = home_beds['Residential']
        else:
            res_bed = None
        if 'Residential dementia' in home_beds:
            res_dem = home_beds['Residential dementia']
        else:
            res_dem = None
        if 'Nursing' in home_beds:
            nus_bed = home_beds['Nursing']
        else:
            nus_bed = None
        if 'Nursing dementia' in home_beds:
            nus_dem = home_beds['Nursing dementia']
        else:
            nus_dem = None
        bed = Bed.objects.create(res_beds = res_bed, res_dem_beds = res_dem,nus_beds = nus_bed, nus_dem_beds = nus_dem )
        home = Home.objects.create(
            name = home_name, vacant_beds = home_vacant_beds, beds = bed, page_number = page_number, id = home_id
        )
        home_list.append((home_vacant_beds,home_name, home_id,home_beds,res_bed,res_dem,nus_bed,nus_dem, home_id))      
        

    stuff = {
        'home_list': home_list,
        'page_number':page_number
    }
    return render(request, 'beds/stuff.html',stuff)

#Changes the amount of bed vacancies
def add_bed(request ,home_id):
    home = get_object_or_404(Home, id=home_id)
    print(home)
    print(home.beds.nus_beds)
    if "remove_res" in request.GET:
        home.beds.res_beds -= 1
        home.vacant_beds += 1
        home.beds.save()
        home.save()
    elif "add_res" in request.GET:
        home.beds.res_beds += 1
        home.vacant_beds -= 1
        home.beds.save()
        home.save()
    elif "remove_res_dem" in request.GET:
        home.beds.res_dem_beds -= 1
        home.vacant_beds += 1
        home.beds.save()
        home.save()
    elif "add_res_dem" in request.GET:
        home.beds.res_dem_beds += 1
        home.vacant_beds -= 1
        home.beds.save()
        home.save()  
    elif "remove_nus" in request.GET:
        home.beds.nus_beds -= 1
        home.vacant_beds += 1
        home.beds.save()
        home.save()
        print(home.beds.nus_beds)
    elif "add_nus" in request.GET:
        home.beds.nus_beds += 1
        home.vacant_beds -= 1
        home.beds.save()
        home.save()  
    elif "remove_nus_dem" in request.GET:
        home.beds.nus_dem_beds -= 1
        home.vacant_beds += 1
        home.beds.save()
        home.save()  
    elif "add_nus_dem" in request.GET:
        home.beds.nus_dem_beds += 1
        home.vacant_beds -= 1
        home.beds.save()
        home.save()  

    return HttpResponseRedirect(reverse('beds:index'))
    

evalucom/beds/templates/beds/base.html
{% load static%}
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    
<nav class="blue darken-3">
    <div class="container nav-wrapper #1565c0 ">
        <div class = "nhs"></div>
        <a href="/" class="brand-logo">NHS beds</a>
        <ul id = "nav-mobile" class="right">
            <li><a href="/">Home</a></li>
        </ul>
    </div>
</nav>
<div class = "container">
    <h2>Welcome to NHS bed vacancy manager</h2>
    {% block content%}

    {% endblock content%}
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

evalucom/beds/templates/beds/stuff.html
{% extends 'beds/base.html'%}

{% block content%}
    <form class="form-inline" action="{% url 'beds:voyage' page_number %}" method="GET">
        {% csrf_token %}
        <div style="display: flex; justify-content: space-evenly;">
            {% if page_number != 0%}
            <button class="btn waves-effect waves-light blue darken-3" type="submit" name="previous">Previous
                <i class="material-icons right">arrow_back</i>
            </button>
            {% endif %}
            <button class="btn waves-effect waves-light blue darken-3 float-right" type="submit" name="next">Next
                <i class="material-icons right">arrow_forward</i>
            </button>
        </div>
    </form>
    {% for home in home_list%}
    <div class="card" style="padding: 1 1 1 1;">
        <div class="container">
            <div class="card-header">
                <p class="text-muted">{{home.2}}</p>
              </div>
            <div class="card-body ">
            <h4 class="card-title" id="name">Name: <strong>{{home.1}}</strong></strong></h5>
            <p class="card-text">Bed Vacancies: <strong>{{home.0}}</strong></p>
            <form action="{% url 'beds:add_bed' home.8 %}" method="GET">
                {% csrf_token%}
                {% if home.4 != None %}
                <div class="row">
                    <div class="col">
                        <p>Residential {{home.4}}: </p>
                    </div>
                    <div class="col">
                        {% if home.4 == 0 %}
                        {% else %}
                        <button class="btn waves-effect waves-light  red darken-2" type="submit" name="remove_res">Remove
                            <i class="material-icons right">remove</i>
                        </button>
                        {% endif %}
                        {% if home.0 == 0 or home.0 == None or home.0 == null%}
                        {% else %}
                        <button class="btn waves-effect waves-light blue darken-3" type="submit" name="add_res">Add
                            <i class="material-icons right">add</i>
                        </button>
                        {% endif %}
                    </div>
                </div>
                {% endif %}
                {% if home.5 != None %}
                <div class="row">
                    <div class="col">
                        <p>Residential Dementia {{home.5}}: </p>
                    </div>
                    <div class="col">
                        {% if home.5 == 0%}
                        {% else%}
                        <button class="btn waves-effect waves-light  red darken-2" type="submit" name="remove_res_dem">Remove
                            <i class="material-icons right">remove</i>
                        </button>
                        {% endif %}
                        {% if home.0 == 0 or home.0 == None or home.0 == null%}
                        {% else %}
                        <button class="btn waves-effect waves-light blue darken-3" type="submit" name="add_res_dem">Add
                            <i class="material-icons right">add</i>
                        </button>
                        {% endif %}
                    </div>
                </div>
                {% endif %}
                {% if home.6 != None %}
                <div class="row">
                    <div class="col">
                        <p>Nursing {{home.6}}: </p>
                    </div>
                    <div class="col">
                        {% if home.6 == 0%}
                        {% else%}
                        <button class="btn waves-effect waves-light  red darken-2" type="submit" name="remove_nus">Remove
                            <i class="material-icons right">remove</i>
                        </button>
                        {% endif %}
                        {% if home.0 == 0 or home.0 == None or home.0 == null%}
                        {% else %}
                        <button class="btn waves-effect waves-light blue darken-3" type="submit" name="add_nus">Add
                            <i class="material-icons right">add</i>
                        </button>
    
                        {% endif %}
                    </div>
                </div>
                {% endif %}
                {% if home.7 != None %}
                <div class="row">
                    <div class="col">
                        <p>Nursing Dementia {{home.7}}: </p>
                    </div>
                    <div class="col">
                        {% if home.7 == 0%}
                        {% else%}
                        <button class="btn waves-effect waves-light  red darken-2" type="submit" name="remove_nus_dem">Remove
                            <i class="material-icons right">remove</i>
                        </button>
                        {% endif %}
                        {% if home.0 == 0 or home.0 == None or home.0 == null%}
                        {% else %}
                        <button class="btn waves-effect waves-light blue darken-3" type="submit" name="add_nus_dem">Add
                            <i class="material-icons right">add</i>
                        </button>
    
                        {% endif %}
                    </div>
                </div>
                {% endif %}
            </form>
            </div> 
        </div> 
    </div>
    {% endfor %}
{% endblock content%}